# Generated by Django 4.2.2 on 2023-10-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sermons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='sermons')),
                ('date', models.DateTimeField()),
                ('orateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermons.orateur')),
            ],
        ),
    ]
