# Generated by Django 4.2.2 on 2024-12-29 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OurData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Noms', models.CharField(max_length=100)),
                ('Provenance', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomTheme', models.CharField(max_length=100)),
                ('ThemeDescription', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='sermons')),
                ('ministre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OurData.ministre')),
            ],
        ),
        migrations.CreateModel(
            name='Sermons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='sermons')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('lien', models.URLField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, upload_to='audio')),
                ('Theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermons.theme')),
                ('orateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermons.orateur')),
            ],
            options={
                'verbose_name': 'Sermon',
            },
        ),
    ]
