# Generated by Django 4.2.2 on 2023-10-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermons',
            options={'verbose_name': 'Sermon'},
        ),
        migrations.AddField(
            model_name='sermons',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sermons',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
