# Generated by Django 4.2.2 on 2024-12-27 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0009_temoignages_is_approuve_alter_ministre_contact'),
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermons',
            options={'verbose_name': 'Sermon'},
        ),
        migrations.RenameField(
            model_name='orateur',
            old_name='nom',
            new_name='Noms',
        ),
        migrations.AddField(
            model_name='orateur',
            name='Provenance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sermons',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
        migrations.AddField(
            model_name='sermons',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sermons',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomTheme', models.CharField(max_length=100)),
                ('ThemeDescription', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='sermons')),
                ('ministre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OurData.ministre')),
            ],
        ),
        migrations.AddField(
            model_name='sermons',
            name='Theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermons.theme'),
        ),
    ]
