# Generated by Django 4.2.2 on 2024-12-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='ministre',
        ),
    ]
