# Generated by Django 4.2.2 on 2023-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_alter_sermons_options_sermons_lien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermons',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
    ]
