# Generated by Django 4.2.2 on 2024-12-29 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0001_initial'),
        ('sermons', '0002_remove_theme_ministre'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='ministre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OurData.ministre'),
        ),
    ]
