# Generated by Django 4.2.2 on 2026-04-14 06:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0003_theme_ministre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermons',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='sermons'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='sermons'),
        ),
    ]
