# Generated by Django 4.2.2 on 2023-11-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0003_sermons_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='ministres')),
                ('contact', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
