# Generated by Django 4.2.2 on 2026-09-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0008_ministre_fonction_orateur_link'),
        ('sermons', '0004_alter_sermons_image_alter_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orateur',
            name='ministre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orateurs', to='OurData.ministre'),
        ),
        migrations.AlterField(
            model_name='sermons',
            name='orateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.orateur'),
        ),
    ]
