# Generated by Django 4.2.2 on 2023-11-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0004_ministre_officiel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ministre',
        ),
        migrations.DeleteModel(
            name='Officiel',
        ),
    ]
