# Generated by Django 4.2.2 on 2024-12-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0005_delete_ministre_delete_officiel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orateur',
            old_name='nom',
            new_name='Noms',
        ),
        migrations.AddField(
            model_name='orateur',
            name='Provenance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
