# Generated by Django 4.2.2 on 2024-12-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0006_rename_nom_orateur_noms_orateur_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomTheme', models.CharField(max_length=100)),
                ('ThemeDescription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sermons',
            name='Theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermons.theme'),
        ),
    ]
