# Generated by Django 4.2.2 on 2024-12-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0007_theme_sermons_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, upload_to='sermons'),
        ),
    ]
