# Generated by Django 4.2.2 on 2024-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_room_remove_message_room_remove_message_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name_room', max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='room', max_length=1000000),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='user', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(default='contenu', max_length=1000000),
        ),
    ]
