# Generated by Django 4.2.2 on 2024-01-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_remove_message_content_remove_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='nameroom', max_length=2000),
        ),
    ]
