# Generated by Django 4.2.2 on 2024-02-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messages_delete_message_delete_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='contents',
            new_name='content',
        ),
    ]
