# Generated by Django 4.2.2 on 2026-10-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Messa',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
