# Generated by Django 4.2.2 on 2024-12-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chantre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(upload_to='chamtrepictures')),
            ],
            options={
                'verbose_name': 'Chantre',
            },
        ),
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEvenement', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('VideoEvenement', models.FileField(blank=True, upload_to='VideoEvenement')),
                ('VisuelEvenement', models.ImageField(blank=True, upload_to='EvenementVisuel')),
            ],
            options={
                'verbose_name': 'Evenement',
            },
        ),
        migrations.CreateModel(
            name='Ministre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='ministrespictures')),
                ('contact', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name': 'Ministre',
            },
        ),
        migrations.CreateModel(
            name='Officiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='officielpictures')),
            ],
            options={
                'verbose_name': 'Officiel',
            },
        ),
        migrations.CreateModel(
            name='Temoignages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomDuCroyant', models.CharField(blank=True, max_length=100)),
                ('Audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('Description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignagespictures')),
                ('is_Approuve', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Temoignage',
            },
        ),
    ]
