# Generated by Django 4.2.2 on 2023-11-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministre',
            options={'verbose_name': 'Ministre'},
        ),
        migrations.AlterModelOptions(
            name='officiel',
            options={'verbose_name': 'Officiel'},
        ),
        migrations.AddField(
            model_name='officiel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='officielpictures'),
        ),
        migrations.AlterField(
            model_name='ministre',
            name='photo',
            field=models.ImageField(blank=True, upload_to='ministrespictures'),
        ),
    ]
