# Generated by Django 4.2.2 on 2025-03-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieOfficiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='officiel',
            name='categorieOfficiel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OurData.categorieofficiel'),
        ),
    ]
