# Generated by Django 4.2.2 on 2025-12-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("OurData", "0002_categorieofficiel_officiel_categorieofficiel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Croyant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom et Prénom")),
                (
                    "photo_profil",
                    models.ImageField(
                        upload_to="croyants/profils/",
                        verbose_name="Photo de profil (Bulle)",
                    ),
                ),
                ("adresse", models.CharField(max_length=200, verbose_name="Adresse")),
                (
                    "date_conversion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de conversion"
                    ),
                ),
                (
                    "etat_civil",
                    models.CharField(
                        help_text="Ex: Marié, 3 enfants",
                        max_length=100,
                        verbose_name="État Civil",
                    ),
                ),
                (
                    "ambitions",
                    models.TextField(verbose_name="Sa prière / Ses ambitions"),
                ),
                (
                    "pourquoi_wmb",
                    models.TextField(verbose_name="Pourquoi WMB Tabernacle ?"),
                ),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fidèle / Croyant",
                "verbose_name_plural": "Les Fidèles (Connaissons-nous)",
                "ordering": ["-date_publication"],
            },
        ),
        migrations.CreateModel(
            name="PhotoSouvenir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="croyants/album/")),
                (
                    "legende",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Légende (optionnel)"
                    ),
                ),
                (
                    "croyant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album",
                        to="OurData.croyant",
                    ),
                ),
            ],
        ),
    ]
