# Generated by Django 4.2.2 on 2024-01-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0002_alter_ministre_options_alter_officiel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomDuCroyant', models.CharField(blank=True, max_length=100)),
                ('Audio', models.FileField(blank=True, upload_to='audio')),
                ('Description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='temoignagespictures')),
            ],
            options={
                'verbose_name': 'Temoignage',
            },
        ),
    ]
