# Generated by Django 4.2.2 on 2025-12-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OurData", "0003_croyant_photosouvenir"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClasseEcodim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la classe"),
                ),
                (
                    "tranche_age",
                    models.CharField(max_length=50, verbose_name="Tranche d'âge"),
                ),
                ("description", models.TextField(verbose_name="Ce qu'ils apprennent")),
                ("image", models.ImageField(upload_to="ecodim/classes/")),
                (
                    "couleur_theme",
                    models.CharField(
                        default="bg-blue-500",
                        max_length=20,
                        verbose_name="Couleur (Hex ou Tailwind)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Moniteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(default="Moniteur / Monitrice", max_length=100),
                ),
                ("photo", models.ImageField(upload_to="ecodim/moniteurs/")),
            ],
        ),
    ]
