# Generated by Django 4.2.2 on 2024-02-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0003_temoignages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEvenement', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('VideoEvenement', models.FileField(blank=True, upload_to='VideoEvenement')),
                ('VisuelEvenement', models.ImageField(blank=True, upload_to='EvenementVisuel')),
            ],
            options={
                'verbose_name': 'Evenement',
            },
        ),
    ]
