# Generated by Django 4.2.2 on 2024-02-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0004_evenements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoignages',
            name='Audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='temoignages',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='temoignagespictures'),
        ),
    ]
