# Generated by Django 4.2.2 on 2026-03-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0004_classeecodim_moniteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembreMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('role', models.CharField(max_length=100, verbose_name='Rôle / Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media_presse/', verbose_name='Photo')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Membre Média & Presse',
                'verbose_name_plural': 'Membres Média & Presse',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='moniteur',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Encadreur Écodim', 'verbose_name_plural': 'Encadreurs Écodim'},
        ),
        migrations.AddField(
            model_name='moniteur',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
