# Generated by Django 4.2.2 on 2026-03-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0005_membre_media_et_ordre_moniteur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evenements',
        ),
    ]
