# Generated by Django 4.2.2 on 2024-04-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0005_alter_temoignages_audio_alter_temoignages_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chantre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(upload_to='chamtrepictures')),
            ],
            options={
                'verbose_name': 'Chantre',
            },
        ),
    ]
