# Generated by Django 4.2.2 on 2026-04-14 06:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0006_delete_evenements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantre',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='chamtrepictures'),
        ),
        migrations.AlterField(
            model_name='classeecodim',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='ecodim/classes/'),
        ),
        migrations.AlterField(
            model_name='croyant',
            name='photo_profil',
            field=imagekit.models.fields.ProcessedImageField(upload_to='croyants/profils/', verbose_name='Photo de profil (Bulle)'),
        ),
        migrations.AlterField(
            model_name='membremedia',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media_presse/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='ministre',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='ministrespictures'),
        ),
        migrations.AlterField(
            model_name='moniteur',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='ecodim/moniteurs/'),
        ),
        migrations.AlterField(
            model_name='officiel',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='officielpictures'),
        ),
        migrations.AlterField(
            model_name='photosouvenir',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='croyants/album/'),
        ),
        migrations.AlterField(
            model_name='temoignages',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='temoignagespictures'),
        ),
    ]
