# Generated by Django 4.2.2 on 2024-07-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0006_chantre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministre',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
