# Generated by Django 4.2.2 on 2024-07-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0007_alter_ministre_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officiel',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
