# Generated by Django 4.2.2 on 2026-09-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0007_alter_chantre_photo_alter_classeecodim_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministre',
            options={'ordering': ['ordre', 'Nom'], 'verbose_name': 'Ministre'},
        ),
        migrations.AddField(
            model_name='ministre',
            name='fonction',
            field=models.CharField(blank=True, choices=[('titulaire', 'Pasteur titulaire'), ('associe', 'Pasteur associé'), ('evangeliste', 'Évangéliste'), ('ministre', 'Ministre de la Parole'), ('invite', 'Invité')], max_length=20),
        ),
        migrations.AddField(
            model_name='ministre',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
