# Generated by Django 4.2.2 on 2024-12-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurData', '0008_alter_officiel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignages',
            name='is_Approuve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ministre',
            name='contact',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
