"""
Django settings for church project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv non installé, on utilise os.environ uniquement

#import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-dev-key-change-me-in-production'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')


ALLOWED_HOSTS = ["djojnk.pythonanywhere.com", "127.0.0.1", '.onrender.com','wmbtab.onrender.com', 'www.wmbranhamtabernacle.org']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sermons',
    'OurData',
    'chat',
    'compte',
    'compressor',
    'tailwind',
    'theme',
    'contribution',
    'actualites'

]

#INSTALLED_APPS += ["django_browser_reload"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'church.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'church.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# En production (Render) : utilise PostgreSQL via DATABASE_URL
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'church/static')
]

INTERNAL_IPS = [
    "127.0.0.1",
]
TAILWIND_APP_NAME = 'theme'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
# En production (Render) : utilise le Persistent Disk monté (ex: /data)
# En local : utilise le dossier media/ du projet
MEDIA_ROOT = os.environ.get('MEDIA_ROOT') or str(BASE_DIR / 'media')
AUTH_USER_MODEL = "compte.Utilisateur"

COMPRESS_ROOT = BASE_DIR / 'church/static'

COMPRESS_ENABLED = True

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

# Chemin npm (local dev) - optionnel en prod
NPM_BIN_PATH = os.environ.get('NPM_BIN_PATH', 'npm')
#django_heroku.settings(locals()) 

# ─── Jazzmin Admin Theme ────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    "site_title": "WMB Tabernacle",
    "site_header": "WMB Tabernacle",
    "site_brand": "WMB Tab",
    "site_logo": "logo24.png",
    "login_logo": "logo24.png",
    "site_logo_classes": "img-circle",
    "site_icon": "logo24.png",
    "welcome_sign": "Bienvenue sur l'administration WMB Tabernacle de mont-ngafula",
    "copyright": "WMB Tabernacle de mont-ngafula",

    "search_model": ["sermons.Sermons", "OurData.Temoignages"],

    "topmenu_links": [
        {"name": "Accueil site", "url": "/", "new_window": True},
        {"app": "sermons"},
        {"app": "OurData"},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    "icons": {
        "auth": "fas fa-users-cog",
        "compte.Utilisateur": "fas fa-user",
        "auth.Group": "fas fa-users",
        "sermons.Sermons": "fas fa-bible",
        "sermons.Theme": "fas fa-tags",
        "sermons.Orateur": "fas fa-microphone",
        "OurData.Ministre": "fas fa-praying-hands",
        "OurData.Officiel": "fas fa-user-tie",
        "OurData.Temoignages": "fas fa-hands",
        "OurData.Evenements": "fas fa-calendar-alt",
        "OurData.Chantre": "fas fa-music",
        "OurData.CategorieOfficiel": "fas fa-layer-group",
        "OurData.Croyant": "fas fa-church",
        "OurData.ClasseEcodim": "fas fa-chalkboard-teacher",
        "OurData.Moniteur": "fas fa-user-graduate",
        "OurData.MembreMedia": "fas fa-video",
        "contribution.EvolutionConstruction": "fas fa-hard-hat",
        "contribution.Contribution": "fas fa-hand-holding-usd",
        "actualites.Article": "fas fa-newspaper",
        "actualites.Categorie": "fas fa-bookmark",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": True,

    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "custom_css": "css/admin_custom.css",

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
    },

    "order_with_respect_to": [
        "sermons",
        "OurData",
        "contribution",
        "compte",
        "auth",
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

