# Generated by Django 4.2.2 on 2026-01-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_donateur",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nom (Laisser vide pour Anonyme)",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="ID Transaction PayPal",
                    ),
                ),
                ("date_don", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_don"],
            },
        ),
        migrations.CreateModel(
            name="EvolutionConstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="construction/evolution/")),
                ("date_travaux", models.DateField(verbose_name="Date des travaux")),
                ("description", models.TextField(blank=True)),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_travaux"],
            },
        ),
    ]
