# Generated by Django 4.2.2 on 2026-03-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transaction PayPal (vide si ajout manuel)'),
        ),
    ]
