# Generated by Django 4.2.2 on 2026-04-14 06:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_transaction_id_optionnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionconstruction',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='construction/evolution/'),
        ),
    ]
