# Generated by Django 4.2.2 on 2026-04-14 06:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_couverture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/couvertures/', verbose_name='Image de couverture'),
        ),
    ]
