# Generated by Django 4.2.2 on 2026-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0003_commentaire_articlelike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='est_approuve',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
    ]
