# Generated by Django 4.2.2 on 2024-02-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur'},
        ),
    ]
